### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by zchrissirhcz** [Mzzopublic/C#21]
- 文件编码统一用UTF-8。目前在linux和mac下都无法正常显示中文。
- 文件名统一以".c"为后缀
- 使用<conio.h>头文件的，注明只能在windows下运行，linux/mac下无法直接使用
- 移除所有的".exe"程序，仅保留源码，以减小repo占用空间大小
- main函数统一使用`int main()`而不是`void main()`或`main()`
- `printf()`输出语句中的格式化字符串与实参类型匹配，例如sizeof()的结果应当是"%ld"类型

**Comment by niliu-ptr** [comment]
巴适，快看不下去了
